
  CREATE TABLE "HEALTH_INSURANCE_PLAN" 
   (	"NUM_SEQ_HIP" NUMBER, 
	"PLAN_NAME_HIP" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"PROVIDER_NAME_HIP" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"COVERAGE_TYPE_HIP" VARCHAR2(128 CHAR), 
	"START_DATE_HIP" DATE NOT NULL ENABLE, 
	"END_DATE_HIP" DATE, 
	"POLICY_NUMBER_HIP" VARCHAR2(32), 
	"CREATED_AT_HIP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT_HIP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("NUM_SEQ_HIP")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_HEALTH_PLAN_HIP" 
BEFORE INSERT OR UPDATE ON health_insurance_plan
FOR EACH ROW
BEGIN
    -- Auto-increment ID
    IF INSERTING AND :NEW.num_seq_hip IS NULL THEN
        :NEW.num_seq_hip := seq_health_plan_hip.NEXTVAL;
    END IF;

    -- Auto-update timestamp
    IF UPDATING THEN
        :NEW.updated_at_hip := CURRENT_TIMESTAMP;
    END IF;
END;
/
ALTER TRIGGER "TRG_HEALTH_PLAN_HIP" ENABLE;