
  CREATE TABLE "HEALTH_PLAN_PHONE" 
   (	"NUM_SEQ_HPP" NUMBER, 
	"NUM_SEQ_HIP_HPP" NUMBER NOT NULL ENABLE, 
	"COUNTRY_CODE_HPP" VARCHAR2(8), 
	"AREA_CODE_HPP" CHAR(3), 
	"PHONE_TYPE_HPP" VARCHAR2(16) NOT NULL ENABLE, 
	"PHONE_NUMBER_HPP" VARCHAR2(16) NOT NULL ENABLE, 
	"IS_PRIMARY_HPP" CHAR(1) DEFAULT 'N', 
	"CREATED_AT_HPP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT_HPP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 CHECK (is_primary_hpp IN ('Y','N')) ENABLE, 
	 PRIMARY KEY ("NUM_SEQ_HPP")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "HEALTH_PLAN_PHONE" ADD CONSTRAINT "FK_HEALTH_PLAN_PHONE" FOREIGN KEY ("NUM_SEQ_HIP_HPP")
	  REFERENCES "HEALTH_INSURANCE_PLAN" ("NUM_SEQ_HIP") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_HEALTH_PLAN_PHONE_HPP" 
BEFORE INSERT OR UPDATE ON health_plan_phone
FOR EACH ROW
BEGIN
    -- Auto-increment PK
    IF INSERTING AND :NEW.num_seq_hpp IS NULL THEN
        :NEW.num_seq_hpp := seq_health_plan_phone_hpp.NEXTVAL;
    END IF;

    -- Auto-update timestamp
    IF UPDATING THEN
        :NEW.updated_at_hpp := CURRENT_TIMESTAMP;
    END IF;
END;
/
ALTER TRIGGER "TRG_HEALTH_PLAN_PHONE_HPP" ENABLE;