
  CREATE TABLE "PATIENT_PHONE" 
   (	"NUM_SEQ_PPH" NUMBER, 
	"NUM_SEQ_PTT_PPH" NUMBER NOT NULL ENABLE, 
	"COUNTRY_COD_PPH" VARCHAR2(8), 
	"AREA_CODE_PPH" CHAR(3), 
	"PHONE_TYPE_PPH" VARCHAR2(16) NOT NULL ENABLE, 
	"PHONE_NUMBER_PPH" VARCHAR2(16) NOT NULL ENABLE, 
	"IS_PRIMARY_PPH" CHAR(1) DEFAULT 'N', 
	"CREATED_AT_PPH" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT_PPH" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 CHECK (is_primary_pph IN ('Y','N')) ENABLE, 
	 PRIMARY KEY ("NUM_SEQ_PPH")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PATIENT_PHONE" ADD CONSTRAINT "FK_PATIENT_PHONE" FOREIGN KEY ("NUM_SEQ_PTT_PPH")
	  REFERENCES "PATIENT" ("NUM_SEQ_PTT") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PATIENT_PHONE_PPH" 
BEFORE INSERT OR UPDATE ON patient_phone
FOR EACH ROW
BEGIN
    -- Auto-increment PK
    IF INSERTING AND :NEW.num_seq_pph IS NULL THEN
        :NEW.num_seq_pph := seq_patient_phone_pph.NEXTVAL;
    END IF;

    -- Auto-update timestamp
    IF UPDATING THEN
        :NEW.updated_at_pph := CURRENT_TIMESTAMP;
    END IF;
END;
/
ALTER TRIGGER "TRG_PATIENT_PHONE_PPH" ENABLE;