
  CREATE TABLE "PATIENT" 
   (	"NUM_SEQ_PTT" NUMBER, 
	"FIRST_NAME_PTT" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"LAST_NAME_PTT" VARCHAR2(256 CHAR) NOT NULL ENABLE, 
	"GENDER_PTT" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"DATE_OF_BIRTH_PTT" DATE NOT NULL ENABLE, 
	"SSN_PTT" CHAR(16), 
	"BLOOD_TYPE_PTT" VARCHAR2(3 CHAR), 
	"ALLERGIES_PTT" CLOB, 
	"MEDICAL_CONDITIONS_PTT" CLOB, 
	"CREATED_AT_PTT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT_PTT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 CHECK (gender_ptt IN ('Male', 'Female', 'Other')) ENABLE, 
	 CHECK (blood_type_ptt IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')) ENABLE, 
	 PRIMARY KEY ("NUM_SEQ_PTT")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PATIENT_PTT" 
BEFORE INSERT OR UPDATE ON patient
FOR EACH ROW
BEGIN
    -- Handle auto-increment for PK
    IF INSERTING AND :NEW.num_seq_ptt IS NULL THEN
        :NEW.num_seq_ptt := seq_patient_ptt.NEXTVAL;
    END IF;

    -- Handle updated_at like MySQL ON UPDATE
    IF UPDATING THEN
        :NEW.updated_at_ptt := CURRENT_TIMESTAMP;
    END IF;
END;
/
ALTER TRIGGER "TRG_PATIENT_PTT" ENABLE;